import { defineArrayMember, defineField } from "sanity";

const dresssize = {
  name: "dresssize",
  title: "Dress Size",
  type: "document",
  fields: [
    {
      name: "XS",
      title: "XS",
      type: "number",
    },
    {
      name: "S",
      title: "S",
      type: "number",
    },
  ],
};

const dress = {
  name: "dress",
  title: "Dress",
  type: "document",
  fields: [
    defineField({
      name: "name",
      title: "Name",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    {
      name: "description",
      title: "Description",
      type: "string",
      description: "Give a description for the dress",
    },
    {
      name: "price",
      title: "Price",
      type: "number",
      description: "Price for the dress",
    },
    {
      name: "rrp",
      title: "RRP",
      type: "number",
      description: "Retail price for the dress",
    },
    {
      name: "brand",
      title: "Brand",
      type: "string",
    },
    {
      name: "images",
      title: "Images",
      type: "array",
      of: [{ type: "image" }],
      options: {
        layout: "grid",
      },
    },
    {
      name: "size",
      title: "Size",
      type: "string",
      initialValue: "",
      options: {
        list: [
          { title: "XL", value: "XL" },
          { title: "L", value: "L" },
          { title: "M", value: "M" },
          { title: "S", value: "S" },
          { title: "XS", value: "XS" },
        ],
      },
    },
    {
      name: "xs",
      title: "XS",
      type: "number",
      description: "Quantity of XS sized dresses",
      defaultValue: 0,
    },
    {
      name: "s",
      title: "S",
      type: "number",
      description: "Quantity of S sized dresses",
      defaultValue: 0,
    },
    {
      name: "m",
      title: "M",
      type: "number",
      description: "Quantity of M sized dresses",
      defaultValue: 0,
    },
    {
      name: "l",
      title: "L",
      type: "number",
      description: "Quantity of L sized dresses",
      defaultValue: 0,
    },
    {
      name: "xl",
      title: "XL",
      type: "number",
      description: "Quantity of XL sized dresses",
      defaultValue: 0,
    },
    {
      name: "recommendedSize",
      title: "Recommended Size",
      type: "array",
      of: [
        {
          type: "string",
        },
      ],
      options: {
        list: [
          { title: "XL", value: "XL" },
          { title: "L", value: "L" },
          { title: "M", value: "M" },
          { title: "S", value: "S" },
          { title: "XS", value: "XS" },
        ],
        layout: "grid",
      },
    },
    {
      name: "length",
      title: "Length",
      type: "string",
      initialValue: "",
      options: {
        list: [
          { title: "Maxi", value: "Maxi" },
          { title: "Mini", value: "Mini" },
          { title: "Midi", value: "Midi" },
        ],
      },
    },
    {
      name: "stretch",
      title: "Stretch",
      type: "string",
      initialValue: "",
      options: {
        list: [
          { title: "1", value: "1" },
          { title: "2", value: "2" },
          { title: "3", value: "3" },
        ],
      },
    },
    {
      name: "condition",
      title: "Condition",
      type: "string",
    },
    {
      name: "notes",
      title: "Notes",
      type: "string",
    },
    {
      name: "tags",
      type: "array",
      title: "Tags for item",
      of: [
        {
          type: "string",
        },
      ],
      options: {
        list: [
          { title: "Evening", value: "evening" },
          { title: "Cocktail", value: "cocktail" },
          { title: "Prom", value: "prom" },
          { title: "Formal", value: "formal" },
          { title: "Casual", value: "casual" },
          { title: "Bridesmaid", value: "bridesmaid" },
          { title: "Wedding", value: "wedding" },
          { title: "Party", value: "party" },
          { title: "Black", value: "black" },
          { title: "White", value: "white" },
          { title: "Red", value: "red" },
          { title: "Blue", value: "blue" },
          { title: "Pink", value: "pink" },
          { title: "Green", value: "green" },
          { title: "Yellow", value: "yellow" },
          { title: "Multicolor", value: "multicolor" },
          { title: "Metallic", value: "metallic" },
          { title: "Pastel", value: "pastel" },
          { title: "Mini", value: "mini" },
          { title: "Midi", value: "midi" },
          { title: "Maxi", value: "maxi" },
          { title: "Knee-Length", value: "knee-length" },
          { title: "Tea-Length", value: "tea-length" },
          { title: "XS", value: "xs" },
          { title: "S", value: "s" },
          { title: "M", value: "m" },
          { title: "L", value: "l" },
          { title: "XL", value: "xl" },
          { title: "A-Line", value: "a-line" },
          { title: "Ball", value: "ball" },
          { title: "Bodycon", value: "bodycon" },
          { title: "Fit-and-Flare", value: "fit-and-flare" },
          { title: "Sheath", value: "sheath" },
          { title: "Wrap", value: "wrap" },
          { title: "Slip Dress", value: "slip-dress" },
          { title: "Off-the-Shoulder", value: "off-the-shoulder" },
          { title: "Silk", value: "silk" },
          { title: "Satin", value: "satin" },
          { title: "Lace", value: "lace" },
          { title: "Velvet", value: "velvet" },
          { title: "Chiffon", value: "chiffon" },
          { title: "Sequin", value: "sequin" },
          { title: "Cotton", value: "cotton" },
          { title: "Linen", value: "linen" },
          { title: "Budget", value: "budget" },
          { title: "Mid-range", value: "mid-range" },
          { title: "Premium", value: "premium" },
          { title: "Sleeveless", value: "sleeveless" },
          { title: "Short Sleeve", value: "short-sleeve" },
          { title: "Long Sleeve", value: "long-sleeve" },
          { title: "Cap Sleeve", value: "cap-sleeve" },
          { title: "V-Neck", value: "v-neck" },
          { title: "Scoop", value: "scoop" },
          { title: "Square", value: "square" },
          { title: "Halter", value: "halter" },
          { title: "High Neck", value: "high-neck" },
          { title: "Sweetheart", value: "sweetheart" },
          { title: "Summer", value: "summer" },
          { title: "Winter", value: "winter" },
          { title: "Spring", value: "spring" },
          { title: "Fall", value: "fall" },
          { title: "Trending Now", value: "trending-now" },
          { title: "New Arrivals", value: "new-arrivals" },
          { title: "Bestsellers", value: "bestsellers" },
          { title: "Customer Favorites", value: "customer-favorites" },
        ],
        layout: "grid",
      },
    },
  ],
};

export default dress;
