import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import MobileNav from "@/components/MobileNav";
import UserAuthContextProvider from "@/context/UserAuthContext";
import UserContextProvider from "@/context/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-white "}>
        <UserAuthContextProvider>
          <UserContextProvider>
            <Navigation />
            <MobileNav />
            {children}
            <Footer />
          </UserContextProvider>
        </UserAuthContextProvider>
      </body>
    </html>
  );
}
